from __future__ import annotations

from dataclasses import dataclass

from core import policy_engine


@dataclass(frozen=True)
class RuntimeToolContract:
    intent: str
    description: str
    tool_surface: str
    capability_id: str
    capability_claim: str
    supported: bool
    unsupported_reason: str
    input_schema: dict[str, str]
    output_schema: dict[str, str]
    side_effect_class: str
    approval_requirement: str
    timeout_policy: str
    retry_policy: str
    artifact_emission: str
    error_contract: str

    @property
    def read_only(self) -> bool:
        return self.side_effect_class == "read_only"


def runtime_tool_contracts() -> list[RuntimeToolContract]:
    read_enabled = bool(policy_engine.get("filesystem.allow_read_workspace", True))
    write_enabled = bool(policy_engine.get("filesystem.allow_write_workspace", False))
    sandbox_enabled = bool(policy_engine.get("execution.allow_sandbox_execution", False))
    web_enabled = bool(policy_engine.allow_web_fallback())
    browser_enabled = bool(policy_engine.allow_browser_fallback())
    return [
        RuntimeToolContract(
            intent="workspace.list_tree",
            description="List the visible file and directory tree inside the active workspace.",
            tool_surface="workspace",
            capability_id="workspace.read",
            capability_claim="list files, inspect the workspace tree, search text, and read files in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace read actions are disabled on this runtime.",
            input_schema={"path": "string optional", "limit": "integer optional"},
            output_schema={"entries": "list[workspace_tree_entry]", "truncated": "boolean"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.list_files",
            description="List files or directories inside the active workspace.",
            tool_surface="workspace",
            capability_id="workspace.read",
            capability_claim="list files, inspect the workspace tree, search text, and read files in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace read actions are disabled on this runtime.",
            input_schema={"path": "string optional", "glob": "string optional", "limit": "integer optional"},
            output_schema={"paths": "list[string]", "truncated": "boolean"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="machine.list_directory",
            description="List visible entries inside a safe local directory such as Desktop, Downloads, or Documents.",
            tool_surface="machine",
            capability_id="machine.read",
            capability_claim="inspect safe local directories and grounded host specs on this machine",
            supported=read_enabled,
            unsupported_reason="Safe local directory inspection is disabled on this runtime.",
            input_schema={"path": "string optional", "directories_only": "boolean optional", "limit": "integer optional"},
            output_schema={"entries": "list[directory_entry]", "truncated": "boolean"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="machine.inspect_specs",
            description="Inspect grounded machine hardware and runtime specs for this local host.",
            tool_surface="machine",
            capability_id="machine.read",
            capability_claim="inspect safe local directories and grounded host specs on this machine",
            supported=read_enabled,
            unsupported_reason="Grounded machine inspection is disabled on this runtime.",
            input_schema={},
            output_schema={
                "chip_name": "string",
                "os_name": "string",
                "os_version": "string",
                "cpu_cores": "integer",
                "ram_gb": "number",
                "gpu_name": "string optional",
                "vram_gb": "number optional",
                "accelerator": "string",
                "recommended_model": "string",
            },
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="machine.read_file",
            description="Read a text file inside a safe local directory such as Desktop, Downloads, or Documents.",
            tool_surface="machine",
            capability_id="machine.read",
            capability_claim="inspect safe local directories, read bounded local text files, and grounded host specs on this machine",
            supported=read_enabled,
            unsupported_reason="Safe local file reads are disabled on this runtime.",
            input_schema={"path": "string", "start_line": "integer optional", "max_lines": "integer optional", "verbatim": "boolean optional"},
            output_schema={"lines": "list[numbered_line]", "line_count": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="machine.ensure_directory",
            description="Create a directory inside a safe local directory such as Desktop, Downloads, or Documents.",
            tool_surface="machine",
            capability_id="machine.write",
            capability_claim="create bounded local directories and text files inside Desktop, Downloads, and Documents",
            supported=write_enabled,
            unsupported_reason="Safe local machine writes are disabled on this runtime.",
            input_schema={"path": "string"},
            output_schema={"path": "string", "action": "created|already_present"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="directory_observation",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="machine.write_file",
            description="Write text content to a file inside a safe local directory such as Desktop, Downloads, or Documents.",
            tool_surface="machine",
            capability_id="machine.write",
            capability_claim="create bounded local directories and text files inside Desktop, Downloads, and Documents",
            supported=write_enabled,
            unsupported_reason="Safe local machine writes are disabled on this runtime.",
            input_schema={"path": "string", "content": "string"},
            output_schema={"path": "string", "line_count": "integer", "action": "created|updated"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="machine_file_observation",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.open_builder_draft",
            description="Create a local web0.null builder URL from a title and self-contained code draft.",
            tool_surface="web0",
            capability_id="web0.local_builder",
            capability_claim="generate local Web0 builder draft URLs for self-contained pages without publishing",
            supported=True,
            unsupported_reason="Local Web0 builder draft generation is disabled on this runtime.",
            input_schema={"title": "string", "code": "string", "domain": "string optional"},
            output_schema={"builder_url": "string", "template": "string", "domain": "string optional"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_url",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.create_project",
            description="Start a local web0.null builder project from a template and target .null domain.",
            tool_surface="web0",
            capability_id="web0.builder",
            capability_claim="build a web0.null page locally: create a project, fill slots, add blocks, gate content, preview",
            supported=True,
            unsupported_reason="Local Web0 builder is disabled on this runtime.",
            input_schema={"template_id": "string", "domain": "string", "project_name": "string optional"},
            output_schema={"project_id": "string", "template_id": "string", "domain": "string", "status": "string"},
            side_effect_class="builder_state",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_project",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.fill_slots",
            description="Fill named content slots (title, tagline, sections) on a local web0.null builder project.",
            tool_surface="web0",
            capability_id="web0.builder",
            capability_claim="build a web0.null page locally: create a project, fill slots, add blocks, gate content, preview",
            supported=True,
            unsupported_reason="Local Web0 builder is disabled on this runtime.",
            input_schema={"project_id": "string", "slots": "object"},
            output_schema={"project_id": "string", "updated_slots": "list[string]", "status": "string"},
            side_effect_class="builder_state",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_project",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.add_block",
            description="Append a content block (heading/text/quote/callout/image/divider) to a page in the builder project.",
            tool_surface="web0",
            capability_id="web0.builder",
            capability_claim="build a web0.null page locally: create a project, fill slots, add blocks, gate content, preview",
            supported=True,
            unsupported_reason="Local Web0 builder is disabled on this runtime.",
            input_schema={"project_id": "string", "page_id": "string optional", "block": "object", "position": "integer optional"},
            output_schema={"project_id": "string", "page_id": "string", "block_count": "integer", "status": "string"},
            side_effect_class="builder_state",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_project",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.add_gated_section",
            description="Encrypt a section behind a wallet whitelist and insert it as a gated block (AES-GCM; only the ciphertext ships).",
            tool_surface="web0",
            capability_id="web0.builder",
            capability_claim="gate web0.null content behind a Solana wallet whitelist so only allowed wallets can decrypt it",
            supported=True,
            unsupported_reason="Local Web0 builder is disabled on this runtime.",
            input_schema={"project_id": "string", "page_id": "string optional", "content": "string", "whitelist": "list[string]", "mode": "string optional", "label": "string optional"},
            output_schema={"project_id": "string", "block_id": "string", "wallets_registered": "integer", "status": "string"},
            side_effect_class="builder_state",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_project",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.encrypt_whole_site",
            description="Encrypt every text-bearing block on every page behind one wallet whitelist; only ciphertext remains in the project.",
            tool_surface="web0",
            capability_id="web0.builder",
            capability_claim="gate web0.null content behind a Solana wallet whitelist so only allowed wallets can decrypt it",
            supported=True,
            unsupported_reason="Local Web0 builder is disabled on this runtime.",
            input_schema={"project_id": "string", "whitelist": "list[string]", "mode": "string optional", "label": "string optional"},
            output_schema={"project_id": "string", "blocks_protected": "integer", "status": "string"},
            side_effect_class="builder_state",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_project",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.compile_preview",
            description="Compile the builder project to a self-contained HTML preview without publishing.",
            tool_surface="web0",
            capability_id="web0.builder",
            capability_claim="build a web0.null page locally: create a project, fill slots, add blocks, gate content, preview",
            supported=True,
            unsupported_reason="Local Web0 builder is disabled on this runtime.",
            input_schema={"project_id": "string"},
            output_schema={"project_id": "string", "html": "string", "size_kb": "number", "status": "string"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="builder_preview",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web0.publish",
            description="Publish the builder project to Arweave. Gated off: the publish opt-in and the wallet are both supplied by the trusted caller, never by the model.",
            tool_surface="web0",
            capability_id="web0.publish",
            capability_claim="publish a web0.null page to Arweave only with a trusted-caller opt-in and wallet — never autonomously",
            supported=True,
            unsupported_reason="Web0 publishing is disabled on this runtime.",
            input_schema={"project_id": "string"},
            output_schema={"status": "string", "arweave_txid": "string optional", "permanent_url": "string optional"},
            side_effect_class="network_publish",
            approval_requirement="explicit_user_opt_in",
            timeout_policy="network_default",
            retry_policy="caller_managed",
            artifact_emission="publish_receipt",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="marketplace.search_listings",
            description="Search the knowledge marketplace for shards by keyword or domain tag.",
            tool_surface="marketplace",
            capability_id="marketplace.read",
            capability_claim="browse the knowledge marketplace and buy shards with compute credits for the local node",
            supported=True,
            unsupported_reason="The knowledge marketplace is disabled on this runtime.",
            input_schema={"query": "string optional", "domain_tag": "string optional", "max_results": "integer optional"},
            output_schema={"listings": "list[marketplace_listing]", "count": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="marketplace.purchase_knowledge",
            description="Buy access to a listed shard for the local node, burning the price from its compute-credit balance.",
            tool_surface="marketplace",
            capability_id="marketplace.purchase",
            capability_claim="browse the knowledge marketplace and buy shards with compute credits for the local node",
            supported=True,
            unsupported_reason="Knowledge purchasing is disabled on this runtime.",
            input_schema={"shard_id": "string", "receipt_id": "string optional"},
            output_schema={"ok": "boolean", "reason": "string", "charged_credits": "number", "unlocked": "boolean"},
            side_effect_class="credit_spend",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="idempotent_on_receipt",
            artifact_emission="purchase_receipt",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web.fetch",
            description="Fetch a public web page over HTTP(S) and return bounded text plus honest fetch status.",
            tool_surface="web",
            capability_id="web.fetch",
            capability_claim="fetch public web pages when web access is enabled and report policy, network, or page barriers honestly",
            supported=web_enabled,
            unsupported_reason="Web fetch is disabled by runtime web policy.",
            input_schema={"url": "string", "timeout_seconds": "number optional"},
            output_schema={"status": "ok|disabled_by_policy|missing_dependency|captcha|login_wall|error", "url": "string", "text": "string optional"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="web_fetch_timeout",
            retry_policy="caller_managed",
            artifact_emission="web_observation",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="web.browser_render",
            description="Render a public page with the configured browser engine when browser tools are enabled.",
            tool_surface="web",
            capability_id="web.browser",
            capability_claim="render browser-dependent pages when Playwright is enabled and report disabled, dependency, captcha, login, or ok status",
            supported=browser_enabled,
            unsupported_reason="Browser rendering is disabled by runtime browser policy.",
            input_schema={"url": "string", "timeout_ms": "integer optional", "max_scroll": "integer optional"},
            output_schema={"status": "ok|disabled_by_policy|missing_dependency|captcha|login_wall|error", "final_url": "string", "text": "string optional"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="browser_render_timeout",
            retry_policy="none",
            artifact_emission="web_observation",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.search_text",
            description="Search text inside workspace files and return file/line matches.",
            tool_surface="workspace",
            capability_id="workspace.read",
            capability_claim="list files, search text, and read files in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace read actions are disabled on this runtime.",
            input_schema={"query": "string", "path": "string optional", "glob": "string optional", "limit": "integer optional"},
            output_schema={"matches": "list[file_line_match]", "match_count": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.symbol_search",
            description="Search likely symbol definitions and references in workspace files.",
            tool_surface="workspace",
            capability_id="workspace.read",
            capability_claim="list files, inspect the workspace tree, search text, and read files in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace read actions are disabled on this runtime.",
            input_schema={"symbol": "string", "path": "string optional", "glob": "string optional", "limit": "integer optional"},
            output_schema={"matches": "list[file_line_symbol_match]", "match_count": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.read_file",
            description="Read a workspace file with line numbers.",
            tool_surface="workspace",
            capability_id="workspace.read",
            capability_claim="list files, inspect the workspace tree, search text, and read files in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace read actions are disabled on this runtime.",
            input_schema={"path": "string", "start_line": "integer optional", "max_lines": "integer optional"},
            output_schema={"lines": "list[numbered_line]", "line_count": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="none",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.ensure_directory",
            description="Create a directory inside the active workspace.",
            tool_surface="workspace",
            capability_id="workspace.write",
            capability_claim="create directories, write files, and replace text in the active workspace",
            supported=write_enabled,
            unsupported_reason="Workspace write actions are disabled on this runtime.",
            input_schema={"path": "string"},
            output_schema={"path": "string", "action": "created|already_present"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="directory_observation",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.write_file",
            description="Write full text content to a workspace file.",
            tool_surface="workspace",
            capability_id="workspace.write",
            capability_claim="create directories, write files, and replace text in the active workspace",
            supported=write_enabled,
            unsupported_reason="Workspace write actions are disabled on this runtime.",
            input_schema={"path": "string", "content": "string"},
            output_schema={"path": "string", "line_count": "integer", "action": "created|updated"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="file_diff",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.replace_in_file",
            description="Replace text inside a workspace file.",
            tool_surface="workspace",
            capability_id="workspace.write",
            capability_claim="create directories, write files, and replace text in the active workspace",
            supported=write_enabled,
            unsupported_reason="Workspace write actions are disabled on this runtime.",
            input_schema={"path": "string", "old_text": "string", "new_text": "string", "replace_all": "boolean optional"},
            output_schema={"path": "string", "replacements": "integer"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="file_diff",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.apply_unified_diff",
            description="Apply a unified diff patch inside the active workspace and track rollback metadata.",
            tool_surface="workspace",
            capability_id="workspace.write",
            capability_claim="create directories, write files, patch files, and replace text in the active workspace",
            supported=write_enabled,
            unsupported_reason="Workspace write actions are disabled on this runtime.",
            input_schema={"patch": "string"},
            output_schema={"paths": "list[string]", "engine": "string"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="file_diff",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.git_status",
            description="Report git status for the active workspace or a subdirectory.",
            tool_surface="workspace",
            capability_id="workspace.git",
            capability_claim="inspect git state and working tree changes in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace git inspection is disabled on this runtime.",
            input_schema={"cwd": "string optional"},
            output_schema={"stdout": "string", "stderr": "string", "returncode": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.git_diff",
            description="Show git diff output for the active workspace or a target path.",
            tool_surface="workspace",
            capability_id="workspace.git",
            capability_claim="inspect git state and working tree changes in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace git inspection is disabled on this runtime.",
            input_schema={"cwd": "string optional", "path": "string optional", "cached": "boolean optional"},
            output_schema={"stdout": "string", "stderr": "string", "returncode": "integer"},
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.git_summary",
            description="Summarize grounded git branch counts, current HEAD, and local day-bucketed commit activity for the active workspace.",
            tool_surface="workspace",
            capability_id="workspace.git",
            capability_claim="inspect git state, branch inventory, and commit activity in the active workspace",
            supported=read_enabled,
            unsupported_reason="Workspace git inspection is disabled on this runtime.",
            input_schema={"cwd": "string optional"},
            output_schema={
                "branch": "string",
                "commit": "string",
                "dirty": "boolean",
                "local_branch_count": "integer",
                "remote_branch_count": "integer",
                "total_branch_count": "integer",
                "today_date": "string",
                "today_commit_count": "integer",
                "yesterday_date": "string",
                "yesterday_commit_count": "integer",
                "commit_count_scope": "string",
                "timezone_label": "string",
            },
            side_effect_class="read_only",
            approval_requirement="none",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.rollback_last_change",
            description="Rollback the last NULLA-tracked workspace mutation in the active session.",
            tool_surface="workspace",
            capability_id="workspace.write",
            capability_claim="create directories, write files, patch files, and replace text in the active workspace",
            supported=write_enabled,
            unsupported_reason="Workspace write actions are disabled on this runtime.",
            input_schema={},
            output_schema={"restored_paths": "list[string]", "removed_paths": "list[string]"},
            side_effect_class="workspace_write",
            approval_requirement="runtime_policy",
            timeout_policy="local_only_default",
            retry_policy="none",
            artifact_emission="file_diff",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.run_tests",
            description="Run the workspace test suite or one bounded test command.",
            tool_surface="workspace",
            capability_id="workspace.validate",
            capability_claim="run bounded validation commands in the active workspace",
            supported=sandbox_enabled,
            unsupported_reason="Workspace validation commands are disabled on this runtime.",
            input_schema={"command": "string optional", "cwd": "string optional"},
            output_schema={"stdout": "string", "stderr": "string", "returncode": "integer"},
            side_effect_class="validation_command",
            approval_requirement="runtime_policy",
            timeout_policy="execution_gate_and_sandbox_limits",
            retry_policy="caller_managed",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.run_lint",
            description="Run the workspace linter or one bounded lint command.",
            tool_surface="workspace",
            capability_id="workspace.validate",
            capability_claim="run bounded validation commands in the active workspace",
            supported=sandbox_enabled,
            unsupported_reason="Workspace validation commands are disabled on this runtime.",
            input_schema={"command": "string optional", "cwd": "string optional"},
            output_schema={"stdout": "string", "stderr": "string", "returncode": "integer"},
            side_effect_class="validation_command",
            approval_requirement="runtime_policy",
            timeout_policy="execution_gate_and_sandbox_limits",
            retry_policy="caller_managed",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="workspace.run_formatter",
            description="Run the workspace formatter in check mode by default or apply formatting when explicitly requested.",
            tool_surface="workspace",
            capability_id="workspace.validate",
            capability_claim="run bounded validation commands in the active workspace",
            supported=sandbox_enabled,
            unsupported_reason="Workspace validation commands are disabled on this runtime.",
            input_schema={"command": "string optional", "cwd": "string optional", "apply": "boolean optional"},
            output_schema={"stdout": "string", "stderr": "string", "returncode": "integer"},
            side_effect_class="validation_command",
            approval_requirement="runtime_policy",
            timeout_policy="execution_gate_and_sandbox_limits",
            retry_policy="caller_managed",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="orchestration.execute_envelope",
            description="Execute a bounded queen, coder, or verifier task envelope against the active workspace.",
            tool_surface="orchestration",
            capability_id="workspace.orchestrate",
            capability_claim="execute bounded task envelopes with explicit permissions and receipts in the active workspace",
            supported=read_enabled and sandbox_enabled,
            unsupported_reason="Task envelope execution requires workspace access and bounded execution to be enabled.",
            input_schema={"task_envelope": "task_envelope_v1"},
            output_schema={"task_id": "string", "status": "string", "receipt_count": "integer"},
            side_effect_class="task_orchestration",
            approval_requirement="runtime_policy",
            timeout_policy="execution_gate_and_sandbox_limits",
            retry_policy="caller_managed",
            artifact_emission="execution_receipts",
            error_contract="returns_structured_error_result",
        ),
        RuntimeToolContract(
            intent="sandbox.run_command",
            description="Run one bounded shell command inside the active workspace with network blocked.",
            tool_surface="sandbox",
            capability_id="sandbox.command",
            capability_claim="run bounded local commands in the active workspace with network blocked",
            supported=sandbox_enabled,
            unsupported_reason="Sandbox command execution is disabled on this runtime.",
            input_schema={"command": "string", "cwd": "string optional"},
            output_schema={"stdout": "string", "stderr": "string", "returncode": "integer"},
            side_effect_class="sandbox_command",
            approval_requirement="runtime_policy",
            timeout_policy="execution_gate_and_sandbox_limits",
            retry_policy="caller_managed",
            artifact_emission="command_output",
            error_contract="returns_structured_error_result",
        ),
    ]


def runtime_tool_contract_map() -> dict[str, RuntimeToolContract]:
    return {contract.intent: contract for contract in runtime_tool_contracts()}
